### ISSUE TITLE
Rehooking, preventing hooking after initialization

### ISSUE THREAD

**Issue by unshame** [Vermintide-Modders/Vermintide-Mod-Framework#18]
Add rehooking hooks of the same type to the same object. Order should be saved.
For this, expand hook_data
```lua
local hook_data = {
    active,
    hook,
    handler,
    hook_type,
    obj
}
```
Experimental:
Only allow mod:hook (and mod:origin?) while the mod is initializing.  
For this, add some hidden variable to the mod that is set to true at the very end of new_mod call.  
This should lock down the order of hooks 100%.

**Comment by Dreomite** [comment]
Hooking shouldn't be limited to initialization frame. Some mods can try to hook function of some mod which is initialized after them. Which means restricting should be done after calling `on_all_mods_loaded` event. But this doesn't make any sense, because some mods can hook during this event bypassing the mod loading order.
